import Link from "next/link"
import { ArrowRight, ChevronRight, Crown, Gamepad2, Trophy, Users, Zap, Activity, Target } from "lucide-react"
import { PublicCard, SectionHeading } from "./public-shell"
import { guildDisplayName } from "./data"
import { getGuildPlayers } from "./player-data"
import { getPublicStats, getPublicGames } from "./server-data"

export default async function PublicHome({ params }: { params: Promise<{ guildId: string }> }) {
  const { guildId } = await params
  const base = `/public/${guildId}`
  const [publicPlayers, stats, publicGames] = await Promise.all([
    getGuildPlayers(guildId),
    getPublicStats(guildId),
    getPublicGames(guildId)
  ])
  const leaders = [...publicPlayers].sort((a, b) => b.elo - a.elo).slice(0, 3)
  const podium = [{ player: leaders[1], position: 2 }, { player: leaders[0], position: 1 }, { player: leaders[2], position: 3 }]
  
  const publicStats = [
    ["ONLINE NOW", String(stats.activeGames)],
    ["REGISTERED PLAYERS", String(stats.registeredPlayers)],
    ["GAMES PLAYED", String(stats.totalGames)],
    ["SEASON", "S14"],
  ] as const
  return <div>
    <section className="relative overflow-hidden border-b border-white/[0.06]"><div className="pointer-events-none absolute right-[8%] top-16 hidden size-56 rotate-12 rounded-[2rem] border border-cyan-300/10 lg:block" /><div className="pointer-events-none absolute right-[11%] top-24 hidden size-56 rotate-12 rounded-[2rem] border border-cyan-300/10 lg:block" /><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(34,211,238,.13),transparent_30%),radial-gradient(circle_at_20%_55%,rgba(124,58,237,.1),transparent_26%)]" /><div className="relative mx-auto grid max-w-[95rem] gap-12 px-5 pb-20 pt-20 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:pb-28 lg:pt-28"><div className="pointer-events-none absolute bottom-4 left-1/2 hidden h-px w-2/3 -translate-x-1/2 bg-gradient-to-r from-transparent via-cyan-300/30 to-transparent lg:block" /><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/[0.06] px-3 py-1.5 font-mono text-[10px] tracking-wider text-cyan-200"><Zap className="size-3" /> SEASON 14 · LIVE</div><h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-0.06em] sm:text-7xl">Play sharper.<br /><span className="text-cyan-300">Climb higher.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/55">{guildDisplayName(guildId)} is a competitive home for players who want fair matchmaking, clean stats, and games worth remembering.</p><div className="mt-9 flex flex-wrap gap-3"><Link href={`${base}/leaderboard`} className="flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-[#071016] transition-transform hover:-translate-y-1">Enter the rankings <ArrowRight className="size-4" /></Link><Link href={`${base}/players`} className="rounded-xl border border-white/15 px-5 py-3 text-sm font-bold text-white/80 transition-colors hover:bg-white/[0.08]">Meet the players</Link></div></div><PublicCard className="relative overflow-hidden p-6 sm:p-7"><div className="absolute -right-14 -top-14 size-40 rounded-full bg-cyan-400/10 blur-3xl" /><div className="mb-7 flex items-center justify-between"><span className="font-mono text-[10px] tracking-[.2em] text-white/45">COMMUNITY STATUS</span><span className="flex items-center gap-2 font-mono text-[10px] text-emerald-300"><i className="size-1.5 rounded-full bg-emerald-400 shadow-[0_0_8px_#34d399]" /> ONLINE</span></div><div className="grid grid-cols-2 gap-3">{publicStats.map(([label, value]) => <div key={label} className="rounded-xl border border-white/[0.07] bg-black/20 p-4"><p className="font-mono text-[10px] text-white/35">{label}</p><p className="mt-2 text-2xl font-black tracking-tight">{value}</p></div>)}</div><div className="mt-5 flex items-center gap-2 border-t border-white/[0.08] pt-5 text-xs text-white/45"><Activity className="size-3.5 text-cyan-300" /> ELO-based matchmaking is active</div></PublicCard></div></section>
    <section className="mx-auto max-w-[95rem] px-5 pb-10 pt-16 sm:px-8 sm:pt-20"><SectionHeading eyebrow="THE SEASON BOARD" title="The names setting the pace." description="Track the players, matches, and moments defining the current climb." /><div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{publicStats.map(([label, value]) => <div key={label} className="rounded-xl border border-white/[0.08] bg-white/[0.02] px-4 py-3"><p className="font-mono text-[9px] tracking-[.18em] text-white/35">{label}</p><p className="mt-1 text-xl font-black text-cyan-100">{value}</p></div>)}</div><div className="mx-auto mt-12 grid max-w-5xl items-end gap-4 md:grid-cols-3">{podium.map(({ player, position }) => player && <Link key={player.id} href={`${base}/players/${player.slug}`}><PublicCard className={`relative overflow-visible p-5 text-center ${position === 1 ? "order-first border-amber-300/35 bg-amber-300/[0.08] md:order-none md:-translate-y-5" : ""}`}><div className={`absolute -top-5 left-1/2 grid size-10 -translate-x-1/2 place-items-center rounded-full border-2 text-sm font-black ${position === 1 ? "border-amber-200 bg-amber-300 text-[#071016]" : "border-white/30 bg-white/90 text-[#071016]"}`}>{position === 1 ? <Crown className="size-4" /> : position}</div><img src={`https://mc-heads.net/bust/${player.name}`} alt={`${player.name} Minecraft avatar`} className="mx-auto mt-5 h-20 w-20 rounded-2xl border border-white/15 bg-black/20 object-cover object-top shadow-[0_0_28px_rgba(34,211,238,.14)]" /><h2 className="mt-4 text-xl font-black">{player.name}</h2></PublicCard></Link>)}</div></section>
    <section className="mx-auto max-w-[95rem] px-5 pb-14 sm:px-8"><div className="mb-4 flex items-center justify-between"><p className="font-mono text-[10px] tracking-[.2em] text-white/30">EXPLORE THE NETWORK</p><span className="h-px flex-1 bg-white/[0.08] ml-4" /></div><div className="grid gap-4 md:grid-cols-3">{[["Players", "Browse competitors and find the names shaping the season.", Users, "/players"], ["Games", "Track recent matches, modes, maps, and results.", Gamepad2, "/games"], ["Leaderboard", "See who is leading the network across every ranked queue.", Trophy, "/leaderboard"]].map(([title, desc, Icon, href]) => <Link href={`${base}${href}`} key={title as string}><PublicCard className="group h-full p-6 transition-transform hover:-translate-y-1"><div className="mb-9 flex justify-between"><span className="grid size-10 place-items-center rounded-xl bg-white/[0.07] text-cyan-300"><Icon className="size-5" /></span><ChevronRight className="size-4 text-white/25 transition-transform group-hover:translate-x-1" /></div><h3 className="text-xl font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-white/45">{desc as string}</p></PublicCard></Link>)}</div></section>
    <section className="mx-auto max-w-[95rem] px-5 pb-24 sm:px-8"><PublicCard className="overflow-hidden p-6 sm:p-8"><div className="mb-6 flex items-end justify-between"><div><p className="font-mono text-[10px] tracking-[.2em] text-cyan-300">MATCH ACTIVITY</p><h2 className="mt-2 text-2xl font-black">Latest games</h2></div><Link href={`${base}/games`} className="text-xs font-bold text-cyan-300">View all <ArrowRight className="ml-1 inline size-3" /></Link></div><div className="divide-y divide-white/[0.07]">{publicGames.length > 0 ? publicGames.slice(0, 4).map(game => <div key={game.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-cyan-300/10 text-cyan-300"><Target className="size-3.5" /></span><div><span className="font-mono text-xs text-white/35">{game.id}</span><span className="ml-3 text-sm font-bold">{game.winner}</span><span className="ml-3 rounded bg-white/[0.06] px-2 py-1 font-mono text-[10px] text-white/45">{game.map}</span></div></div><div className="flex items-center gap-5 font-mono text-xs"><span className="text-white/60">{game.score}</span><span className="text-white/30">{game.time}</span></div></div>) : <div className="py-8 text-center font-mono text-xs text-white/35">No games recorded yet.</div>}</div></PublicCard></section>
    <section className="mx-auto grid max-w-[95rem] gap-4 px-5 pb-24 sm:px-8 md:grid-cols-2 lg:grid-cols-4">
      {[['About', '/about', 'A fair, transparent place to queue, compete, and track every step of the climb.'], ['Creators', '/creators', 'Meet the players, streamers, and community voices keeping the competition moving.'], ['Partners', '/partners', 'Explore the teams and organizations helping build better ranked play.'], ['Support', '/support', 'Find answers, community guidance, and the right place to ask.']].map(([title, href, copy]) => <Link key={title} href={`${base}${href}`}><PublicCard className="group h-full p-5 transition-transform hover:-translate-y-1"><p className="font-mono text-[10px] tracking-[.2em] text-cyan-300">{"// "}{title.toUpperCase()}</p><h2 className="mt-3 text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-white/45">{copy}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-cyan-300">Explore <ArrowRight className="size-3 transition-transform group-hover:translate-x-1" /></span></PublicCard></Link>)}
    </section>
  </div>
}
